import ActionManager from './ActionManager'
export { Animation } from './ActionManager'
export { MoveTo, MoveBy } from './ActionMove'
export { ScaleTo, ScaleBy } from './ActionScale'
export { RotateTo, RotateBy } from './ActionRotate'
export { FadeIn, FadeOut } from './ActionFade'
export { SkewTo, SkewBy } from './ActionSkew'
export { PivotTo, PivotBy } from './ActionPivot'
export { Blink } from './ActionBlink'
export { TintTo, TintBy } from './ActionTint'
export { AlphaTo, AlphaBy } from './ActionAlpha'
export { Repeat } from './ActionRepeat'
export { Sequence } from './ActionSequence'
export { Spawn } from './ActionSpawn'
export { DelayTime } from './ActionDelay'
export { CallFunc } from './ActionCallFunc'
export { default as Action } from './Action'
export const actionManager = new ActionManager()
