export const sf_progress_bg = 'Texture/progress_bg.png'
export const sf_progress_bar = 'Texture/progress_bar.png'
export const sf_dialog_name = 'Texture/dialog-name.png'
export const sf_crash = 'Texture/crash.png'
export const sf_spineboy_pma = 'Spine/spineboy-pma.png'
export const sf_bitmap_2_yellow = 'Font/bitmap2-yellow.png'